[package]
name = "osclientcerts"
version = "0.1.0"
authors = ["Dana Keeler <dkeeler@mozilla.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
core-foundation = "0.6"
hex = "0.3"
lazy_static = "1"
sha2 = "0.8"

[build-dependencies]
bindgen = "0.49"

[lib]
name = "osclientcerts"
crate-type = ["cdylib"]
